### ISSUE TITLE
Representatives

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/revisiting-axelrod-second#3]
How about a section to test the claims made for the [representative strategies](https://github.com/Axelrod-Python/axelrod-fortran/issues/49)?

We could test whether the claim holds good for the original 58 strategies and then whether it still holds good for any of further strategies.

**Comment by drvinceknight** [comment]
If we decide to train strategies we can train them against this representative list. It seems we're over fitting with our training so this could be nice.

**Comment by drvinceknight** [comment]
Closed by 0a190a9 (work done to replicate this).
